12th-EWHA-LIKELION-DEMODAY/FE

src/components/FAB/FAB.style.ts, src/pages/MainPage/components/Arrow.style.ts, src/pages/MainPage/components/Header.style.ts, src/pages/MainPage/components/landing/Carousel.style.ts, src/pages/MainPage/components/landing/Landing.style.ts, src/pages/MainPage/components/scroll/Scroll.style.ts, src/styles/global.ts
- 내부 QA 반영
<br/>
1. 최대 너비 425px로 수정
2. FAB 위치 수정
3. 메인 페이지 위쪽 패딩 값 수정
<br/>
<br/>
<br/>
=> [Fix] 내부 QA 반영

src/api/post.ts, src/api/search.ts, src/components/ItemList/ItemList.style.ts, src/components/ItemList/ItemList.tsx, src/hooks/useInfiniteQuery.ts, src/pages/ListPage/ListPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Feat] 무한스크롤 구현 완료 및 페이지 이동 연결

src/pages/MadePage/components/MadeTopbar.tsx, src/pages/MyPage/MyPage.tsx, src/pages/SearchPage/ImgSearchPage.style.ts
만들기 페이지에서 X 버튼 눌렀을 때 진입한 페이지로 돌아갈 수 있도록 라우팅 처리하였습니다.
만들기 페이지에서 post 완성 후 마이페이지로 이동할 때 애니메이션 적용되지 않도록 수정하였습니다.
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 라우팅 관련 QA 반영

src/components/ItemList/ItemList.tsx, src/hooks/useInfiniteQuery.ts, src/pages/DetailPage/DeatilPage.style.ts, src/pages/DetailPage/DetailPage.tsx, src/pages/ListPage/ListPage.style.ts, src/pages/ListPage/ListPage.tsx, src/pages/ListPage/components/Onboarding.tsx, src/pages/SearchPage/components/SearchHistory.tsx
=> [Fix] 기디 1차 QA반영1

src/pages/AuthPage/components/Auth.style.ts, src/pages/MyPage/components/MyGridBox.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Chore] 공유페이지 애니메이션 수정 완료

src/api/auth.ts, src/pages/AuthPage/LoginPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 카카오로그인 clearCookies() 추가

src/api/my.ts
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 공유페이지 API 호출 로직 수정

src/pages/MadePage/components/MadeTopbar.tsx, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/components/MyGridBox.tsx
<br/>
MadeTopbar에서 ``` isOpneded: false```를 ```isGridVisible: true```로 변경했고,
MyPage에서도 관련 코드 수정했습니다!
<br/>
<br/>
<br/>
=> [Fix] my-made navigate 오류 수정

src/components/ItemList/ItemList.tsx, src/pages/DetailPage/DetailPage.tsx, src/pages/ListPage/ListPage.tsx, src/pages/ListPage/components/ListPopup.tsx
- 상세페이지 미트볼 조건 수정
- 상세 빈 박스 커짐 방지
- 목록페이지 개수 제한 팝업 추가
<br/>
<br/>
<br/>
<br/>
=> [Fix] 상세페이지 미트볼 조건 수정, 상세 빈 박스 커짐 방지, 목록페이지 개수 제한 팝업 추가

src/components/Item/Item.style.ts, src/components/ItemList/ItemList.style.ts
=> [Fix] 기디 1차 QA 반영 완료

src/components/Item/Item.style.ts, src/components/ItemList/ItemList.style.ts, src/components/ItemList/ItemList.tsx
=> [Style] Item 컴포넌트 관련 스타일 수정

src/pages/DetailPage/DeatilPage.style.ts, src/pages/DetailPage/DetailPage.tsx
=> [Fix] 상세페이지 이미지 내보내기 완료

src/pages/MyPage/MyPage.style.ts, src/pages/MyPage/MyPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Chore] 마이페이지 스타일 수정

src/pages/MainPage/components/Arrow.style.ts, src/pages/MainPage/components/landing/Carousel.style.ts
- 메인1 캐러셀 위치 수정
<br/>
<br/>
<br/>
<br/>
=> [Fix] 메인1 캐러셀 위치 수정

src/constants/main/mainCategory.ts, src/pages/MainPage/components/Arrow.style.ts, src/pages/MainPage/components/landing/Carousel.style.ts
- 메인1 캐러셀 위치 재수정
<br/>
<br/>
<br/>
<br/>
=> [Fix] 메인1 캐러셀 위치 재수정

public/svgs/search.svg, src/assets/Search.tsx, src/components/FAB/FAB.tsx, src/pages/DetailPage/DeatilPage.style.ts, src/pages/DetailPage/DetailPage.tsx, src/pages/ListPage/ListPage.tsx, src/pages/SearchPage/components/SearchBar.style.ts, src/pages/SearchPage/components/SearchBar.tsx, src/pages/SearchPage/components/SearchImgBar.tsx
- 상세페이지 문구랑 버튼 위치 조정
- 상세페이지 info 텍스트 정렬 추가
- 검색페이지 화이트모드 fill 변경
- FAB 일상에서 stroke 검정으로 수정
- 화이트모드에서 목록페이지 라이팅 변경
- 상세 info 텍스트 너비 제한 및 말줄임표 추가
- 상세 스크롤에 따른 배경+프레임 스케일 달라짐 방지
<br/>
<br/>
<br/>
<br/>
=> [Fix] 기디 2차 QA 반영

src/pages/DetailPage/DeatilPage.style.ts
=> [Fix] 상세 배경 overflow 제거

src/pages/DetailPage/DeatilPage.style.ts
=> [Fix] 상세페이지 모바일 스크롤 문제 테스트

src/pages/DetailPage/DeatilPage.style.ts, src/pages/DetailPage/DetailPage.tsx, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/components/MyGridBox.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 2차 QA 수정사항 반영

src/pages/MainPage/MainPage.tsx, src/pages/MainPage/components/Header.tsx, src/styles/global.ts
- 메인 페이지 이전 컴포넌트 이동 기능 추가
<br/>
<br/>
<br/>
<br/>
=> [Feat] 메인 페이지 이전 컴포넌트 이동 기능 추가

src/pages/MyPage/MyPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 마이페이지 오류 재수정

src/api/made.ts, src/assets/Delete.tsx, src/pages/MadePage/components/MadeTopbar.tsx, src/pages/MadePage/components/ThumbSearchTap.tsx
Delete svg 모드 따라 색깔 변경되도록 수정했습니다.
만들기 -> 마이 넘어갈 때 데이터 업데이트 되기 전에 넘어가서 0.5초 지연 후 넘어가도록 설정했습니다.
만들기 topbar z-index 수정 완료했습니다.
제목 필드 초기화 관련해서 수정했습니다. (추후 확인 및 점검 필요할 것 같습니다!)
<br/>
=> [Fix] 2차 QA 반영

src/pages/MyPage/MyPage.tsx, src/pages/MyPage/ShareMyPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] url 클립보드 복사 및 팝업 관련 로직 수정

src/api/made.ts, src/assets/Delete.tsx, src/pages/MadePage/components/MadeTopbar.tsx
백엔드 이슈 제외한 3차 QA에서 담당 파트 부분 해결 완료하였습니다.
-> 만들기 페이지에서 마이 페이지로 만들고 바로 이동했을 때 데이터가 바로 안 뜨는 문제는 전송 시간 때문에 생기는 어쩔 수 없는 문제일까요..? 제 로컬에서는 잘 동작하는 터라 다른 분들도 같은 문제 있으시면 연락 부탁드립니다 ㅠ.ㅠ
<br/>
=> [fix] 3차 QA 반영

src/api/my.ts, src/api/post.ts, src/api/search.ts, src/components/ItemList/ItemList.tsx, src/pages/DetailPage/components/DetailMenu.tsx, src/pages/ListPage/ListPage.tsx, src/pages/ListPage/components/Onboarding.style.ts, src/pages/ListPage/components/Onboarding.tsx, src/pages/SearchPage/SearchPage.tsx, src/pages/SearchPage/components/SearchBar.tsx, src/pages/SearchPage/components/SearchResult.tsx
- 온보딩 시작 시 페이드인 추가
- 상세 닫기로 검색 돌아올 때 검색어 유지
<br/>
<br/>
<br/>
<br/>
=> [Fix] 기디 2차 QA 반영 완료

src/pages/MyPage/ShareMyPage.tsx, src/pages/MyPage/components/MyGridBox.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Chore] 공유페이지 기본이미지 다크모드 분리

src/api/made.ts, src/assets/Delete.tsx, src/pages/MadePage/components/MadeTopbar.tsx, src/pages/SearchPage/ImgSearchPage.tsx
white 등록 에러 나는 부분 백엔드 측과 소통하여 해결하였습니다.
또한 delete 색 부분 로직 수정하였습니다.
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] white 등록 에러 수정 + delete 수정

src/pages/MainPage/components/scroll/Carousel.tsx
- 이미지 로딩 개선?
<br/>
1. 이미지 로딩 개선
<br/>
<br/>
<br/>
=> [Feat] 이미지 로딩 개선

public/svgs/Frame-TREE.svg, src/assets/FrameTree.tsx
- 트리 프레임 storkeWidth 조정
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Hotfix] 트리 프레임 storkeWidth 조정

src/components/Item/Item.style.ts, src/components/ItemList/ItemList.style.ts
=> [Style] 목록 item이미지 늘어남 방지

src/pages/MyPage/MyPage.style.ts, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/ShareMyPage.tsx
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Chore] 마이페이지 높이 수정

src/api/made.ts, src/pages/DetailPage/components/DetailMenu.tsx, src/pages/MadePage/components/MadeTopbar.tsx, src/pages/MadePage/components/UploadTitle.tsx
백엔드 카테고리 '앱' -> '어플'로 전송되도록 수정했습니다.
마이페이지 이동할 때 함수 비동기로 동작하도록 수정했습니다. 
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Hotfix] 백엔드 연동 에러 해결

src/pages/DetailPage/DetailPage.tsx, src/pages/ListPage/ListPage.tsx, src/pages/MyPage/components/MyGridBox.tsx
=> [Fix] 공유페이지에서 접속 시 미트볼에서 닫힘버튼으로 수정, 온보딩 뒤로가기 시 막기

src/api/made.ts, src/api/my.ts, src/contexts/ThemeContext.tsx, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/ShareMyPage.tsx, src/routes/Router.tsx
- 공유 페이지 다크 모드 반영
<br/>
1. 공유 페이지 다크 모드 반영
<br/>
<br/>
<br/>
=> [Fix] 공유 페이지 다크 모드 반영

src/contexts/UserContext.tsx, src/pages/MyPage/components/MyGridBox.tsx
- 공유 페이지에서 만들기 페이지 이동 제한
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Feat] 공유 페이지에서 만들기 페이지 이동 제한

src/pages/MyPage/MyPage.style.ts, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/ShareMyPage.tsx
- 링크 복사 팝업 코드 수정
<br/>
1. 링크 복사 팝업 코드 수정
<br/>
<br/>
<br/>
=> [Fix] 링크 복사 팝업 코드 수정

src/api/post.ts, src/api/search.ts, src/hooks/useInfiniteQuery.ts, src/pages/ListPage/ListPage.tsx
- 무한스크롤 코드 수정
<br/>
1. 무한스크롤 코드 수정
<br/>
<br/>
<br/>
=> [Fix] 무한스크롤 코드 수정

src/pages/MadePage/MadePage.tsx, src/pages/MadePage/components/MadePopup.tsx, src/pages/MadePage/components/MadeTopbar.tsx
500 에러 발생시 모달 추가했습니다.
이미지 사이즈 줄이는 건 백엔드 측에서 해결해주신다고 해서 우선 해당 사항 반영합니다.
다들 연말에 파이팅...🥲🎄
<br/>
1. 작업 내용
<br/>
<br/>
<br/>
=> [Fix] 500 에러 발생시 모달 추가
